import FloatingNavigation from "@/components/frontend/FloatingNavigation";
import "./app.css";
import type { Metadata } from "next";
import Footer from "@/components/frontend/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function FrontendLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<body>
			<FloatingNavigation />
			{children}
			<Footer />
		</body>
	);
}
