import FloatingNavigation from "@/components/frontend/FloatingNavigation";
import "./app.css";
import type { Metadata } from "next";
import Footer from "@/components/frontend/Footer";
import GlassNavbar from "@/components/frontend/bottomNavigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function FrontendLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<body>
			<div className="block md:hidden">
				<GlassNavbar/>
			</div>
			<div className="hidden md:block">
				<FloatingNavigation />
			</div>
			{children}
			<Footer />
		</body>
	);
}
